# Generated by Django 3.2.3 on 2021-05-27 09:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hexocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fetch_a_link_permission', models.BooleanField(max_length=256)),
                ('thumbnail_sizes', models.CharField(max_length=256)),
                ('original_img_permission', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('data_add', models.DateTimeField(auto_now_add=True)),
                ('seconds_to_exp', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(3000)])),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SizesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountTier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexocean.accounttier')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexocean.size')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountTier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexocean.accounttier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
