# Generated by Django 3.2.3 on 2021-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0002_accounttier_link_profile_size_sizeslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttier',
            name='thumbnail_sizes',
        ),
        migrations.AlterField(
            model_name='accounttier',
            name='fetch_a_link_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounttier',
            name='original_img_permission',
            field=models.BooleanField(default=False),
        ),
    ]
