# Generated by Django 3.2.3 on 2021-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0006_img_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
