# Generated by Django 3.2.3 on 2021-05-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0008_auto_20210527_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullImg',
            fields=[
                ('img_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hexocean.img')),
            ],
            bases=('hexocean.img',),
        ),
    ]
