# Generated by Django 3.2.3 on 2021-05-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0009_fullimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='FullImg',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hexocean.fullimg'),
            preserve_default=False,
        ),
    ]
