# Generated by Django 3.2.3 on 2021-05-30 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0010_link_fullimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='FullImg',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='Image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hexocean.img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='seconds_to_exp',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
