# Generated by Django 3.2.3 on 2021-05-30 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0011_auto_20210530_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
