# Generated by Django 3.2.3 on 2021-05-30 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hexocean.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hexocean', '0013_rename_seconds_to_exp_link_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='seconds',
        ),
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='imgs', validators=[hexocean.validators.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='TmpLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hexocean.link')),
                ('seconds', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(3000)])),
            ],
            bases=('hexocean.link',),
        ),
    ]
